In [1]:
import pandas as pd
import requests

In [2]:
query_user = "What's the cheapeast journey from Heathrow to Charles de Gaullie departing september 10th 2023 for one adult and returning on the 12th september 2023"
# query = f'''Based on the user query: {query_user} do the following: 
# Return the price, airline, individual legs, date, origin, and destination airport of the journey.
# Some journeys are indirect meaning they have multiple legs, remember to factor this into your calculation. The prices quoted are the total price for the journey.
# '''

query = f'''
Based on the user query: "{query_user}", perform the following tasks:

1. Parse the user's request to identify the Origin Airport, Destination Airport, and Departure Date.

2. Retrieve all journeys from the database that match the identified criteria.

3. For each matching journey, collect the following information:
   - Price: This is the total cost of the journey.
   - Airline: The company operating the flight.
   - Legs: Each journey may consist of one or more legs. A leg represents a flight from one airport to another. Capture the details of each leg, which may include the departure airport, arrival airport, departure time, and arrival time.
   - Date: The departure date of the journey.
   - Origin: The departure airport of the journey.
   - Destination: The arrival airport of the journey.

4. Some journeys may be indirect, meaning they consist of multiple legs. Ensure you capture the details of all individual legs in these cases.

5. After retrieving all the relevant journey details, identify the journey with the lowest total price. This is considered the "cheapest" journey.

6. Return the details of the cheapest journey, including the price, airline, individual legs, date, origin airport, and destination airport.
'''

In [3]:
# read keys
import yaml
import os

def read_config():
    # Get the directory of the current script
    # script_dir = os.path.dirname(os.path.realpath(__file__))
    script_dir = "../src/"

    # Construct the full path to the configuration file
    file_path = os.path.join(script_dir, "apikeys.yml")

    with open(file_path, 'r') as stream:
        try:
            configs = yaml.safe_load(stream)
            api_key = configs['amadeues_flights']['api_key']
            api_secret = configs['amadeues_flights']['api_secret']
            openai_key = configs['openai']['openai_key']
            return api_key, api_secret, openai_key
        except yaml.YAMLError as exc:
            print(exc)
            
    return api_key, api_secret, openai_key

class SingletonToken:
    __token = None

    @classmethod
    def set_token(cls, token):
        cls.__token = token

    @classmethod
    def get_token(cls):
        return cls.__token

api_key, api_secret, openai_key = read_config()

In [4]:
def journey_data(response_flights_data, response_airline_lookup_data):
    # Load the data into a DataFrame
    df = pd.DataFrame(response_flights_data)
    df_airline_codes = pd.json_normalize(response_airline_lookup_data)
    
    # Extract itineraries, validatingAirlineCodes, price (total and currency) and id into separate dataframes
    df_itineraries = df[['id', 'itineraries']].explode('itineraries').reset_index(drop=True)
    
    # In the itineraries column, each cell is a dictionary. So, we need to convert those dictionaries into separate columns.
    df_itineraries = df_itineraries.join(pd.json_normalize(df_itineraries['itineraries'])).drop(columns='itineraries')
    
    # At this point, 'segments' column is a list of dictionaries where each dictionary represents a leg of the journey.
    # We want each leg to be a separate row in the dataframe. So, explode the 'segments' column.
    df_itineraries = df_itineraries.explode('segments').reset_index(drop=True)
    
    # Add a 'leg_id' column to identify each leg of the journey
    df_itineraries['leg_id'] = df_itineraries.groupby('id').cumcount() + 1
    
    # Now, convert the dictionaries in the 'segments' column into separate columns
    df_segments = pd.json_normalize(df_itineraries['segments'])
    
    # To avoid overlapping columns, add a prefix to the column names of the new dataframe
    df_segments.columns = ['flight_' + str(col) for col in df_segments.columns]
    
    # Now join the original dataframe with the new one
    df_itineraries = df_itineraries.join(df_segments).drop(columns='segments')
    
    df_validatingAirlineCodes = df[['id', 'validatingAirlineCodes']]
    
    # For the price column, we only need total and currency. So, extract only those into a new dataframe
    df_price = df['price'].apply(pd.Series)[['total', 'currency']]
    df_price['id'] = df['id']
    
    # Now join these dataframes on the 'id' column
    df_flights = pd.merge(df_itineraries, df_validatingAirlineCodes, on='id')
    df_flights = pd.merge(df_flights, df_price, on='id')
    
    # Create a new column for the total number of legs per journey
    df_flights['total_legs'] = df_flights.groupby('id')['leg_id'].transform('max')
    
    df_flights = df_flights.merge(right=df_airline_codes, how='left', left_on="flight_operating.carrierCode", right_on="iataCode")
    df_flights.rename(columns={"id":"journey_id", "commonName":"airline" }, inplace=True)

    df_flights.drop(columns=["flight_id", "validatingAirlineCodes", "businessName", "flight_operating.carrierCode", "flight_aircraft.code"], inplace=True)

    df_flights.columns = df_flights.columns.str.replace('.', '_')

    return df_flights

In [5]:
from sqlalchemy import create_engine
import pandas as pd
from langchain import SQLDatabase

def load_data(df_flights):
    engine = create_engine('sqlite:///:memory:')

    # Write the data to the SQLite database
    df_flights.to_sql('flights', engine, if_exists='replace', index=False)
    # Check if the data was loaded correctly
    df_loaded = pd.read_sql('SELECT * FROM flights', engine)
    db = SQLDatabase(engine)
    return db

In [6]:
import json
import openai

def get_args(query_user: str) -> str:
    # OpenAI function calling

    """Get's arguments based on client query, returns num_adults, departureDate, destinationLocationCode, originLocationCode"""
    
    function_call = [
    {
      "name": "search_for_flights",
      "description": "Requests flight data from Amadeus API and writes to SQLite database",
      "parameters": {
        "type": "object",
        "properties": {
            "num_adults":{
                "type":"integer",
                "description": '''Based on the query, respond with the number of adults'''
            },
            "departureDate": {
                "type":"string",
                "description": '''Based on the query, respond with the Departure Date. Dates are specified in the ISO 8601 YYYY-MM-DD format. '''
            },
            "returnDate": {
                "type":"string",
                "description": '''Based on the query, respond with the Return Date. Dates are specified in the ISO 8601 YYYY-MM-DD format. '''
            },
            "destinationLocationCode":{
                "type":"string",
                "description": '''Based on the query, respond with an airport IATA code from the city which the traveler is going. E.g CDG for Charles de Gaulle Airport'''
            },
          "originLocationCode": {
            "type": "string",
            "description": '''Based on the query, respond with an airport IATA code from the city which the traveler will depart from. E.g CDG for Charles de Gaulle Airport'''
          },

        },
        "required": ["destinationLocationCode", "originLocationCode", "departureDate", "num_adults"]
      }
    }
    ]
    
    openai.api_key = openai_key

    message = openai.ChatCompletion.create(
        model="gpt-3.5-turbo-0613",
        messages=[{"role": "user", "content": query_user}],
        functions = function_call,
        function_call = 'auto',
        temperature=0
    )
    response_message = message["choices"][0]["message"]["function_call"]["arguments"]

    parsed_data = json.loads(response_message)

    # Accessing variables
    num_adults = parsed_data['num_adults']
    departureDate = parsed_data['departureDate']
    returnDate = parsed_data['returnDate']
    destinationLocationCode = parsed_data['destinationLocationCode']
    originLocationCode = parsed_data['originLocationCode']
    
    print("Number of Adults: ", num_adults)
    print("Departure Date: ", departureDate)
    print("Departure Date: ", departureDate)
    print("Destination Location Code: ", destinationLocationCode)
    print("Origin Location Code: ", originLocationCode)

    return num_adults, departureDate, returnDate, destinationLocationCode, originLocationCode

num_adults, departureDate, returnDate, destinationLocationCode, originLocationCode = get_args(query_user)

Number of Adults:  1
Departure Date:  2023-09-10
Destination Location Code:  CDG
Origin Location Code:  LHR

In [7]:
from amadeus import Client, ResponseError
from datetime import datetime
from langchain.chat_models import ChatOpenAI
from langchain.experimental.plan_and_execute import PlanAndExecute, load_agent_executor, load_chat_planner
from langchain.tools.python.tool import PythonREPLTool
from langchain.llms import OpenAI
from langchain import SerpAPIWrapper
from langchain.agents.tools import Tool
from langchain.tools import tool
from langchain import LLMMathChain
from langchain import OpenAI, SQLDatabase, SQLDatabaseChain


def search_for_flights(originLocationCode, destinationLocationCode, departureDate, returnDate, num_adults) -> SQLDatabase:
    """Requets flight data from Amadeus API and writes to sqllite database and run SQLDatabaseQuery
    originLocationCode: Based on the query, respond with the iataCode for the origin airport,
    destinationLocationCode: Based on the query, respond with the iataCode for the destination airport,
    departureDate: Based on the query, respond with the departure date,
    num_adults: Based on the query, respond with the number of adults
    """

    # Assuming you've defined api_key and api_secret somewhere else
    amadeus = Client(client_id=api_key, client_secret=api_secret)

    # Defining the parameters for the flight
    params = {
        'originLocationCode': originLocationCode,
        'destinationLocationCode': destinationLocationCode,
        'departureDate': departureDate,
        'returnDate': returnDate,
        'adults': num_adults
        # add or modify other parameters according to your needs
    }
    
    try:
        response_flights = amadeus.shopping.flight_offers_search.get(**params)
        
    except ResponseError as error:
        print(f"ResponseError occurred flights: {error}")
        print(f"Error code flights: {error.code}")
        print(f"Error message flights: {error.description}")
        return []  # return an empty list in case of an error

    try:
        response_airline_lookup = amadeus.reference_data.airlines.get()

    except ResponseError as error:
        print(f"ResponseError occurred airline lookup: {error}")
        print(f"Error code airline lookup: {error.code}")
        print(f"Error message airline lookup: {error.description}")

    df_flights = journey_data(response_flights.data, response_airline_lookup.data)
    db = load_data(df_flights)

    return db, df_flights

db, df_flights = search_for_flights(originLocationCode, destinationLocationCode, departureDate, num_adults)
df_flights.info()

InterfaceError: (sqlite3.InterfaceError) Error binding parameter 14 - probably unsupported type.
[SQL: INSERT INTO flights (journey_id, duration, leg_id, "flight_carrierCode", flight_number, flight_duration, "flight_numberOfStops", "flight_blacklistedInEU", "flight_departure_iataCode", flight_departure_terminal, flight_departure_at, "flight_arrival_iataCode", flight_arrival_terminal, flight_arrival_at, flight_stops, total, currency, total_legs, type, "iataCode", "icaoCode", airline) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [('1', 'PT5H55M', 1, 'SK', '532', 'PT2H30M', 0, 0, 'LHR', '2', '2023-09-10T13:55:00', 'ARN', '5', '2023-09-10T17:25:00', None, '125.72', 'EUR', 2, None, None, None, None), ('1', 'PT5H55M', 2, 'SK', '579', 'PT2H35M', 0, 0, 'ARN', '5', '2023-09-10T18:15:00', 'CDG', '1', '2023-09-10T20:50:00', None, '125.72', 'EUR', 2, 'airline', 'SK', 'SAS', 'SAS'), ('2', 'PT1H15M', 1, 'AF', '1381', 'PT1H15M', 0, 0, 'LHR', '3', '2023-09-10T06:20:00', 'CDG', '2E', '2023-09-10T08:35:00', None, '152.28', 'EUR', 1, 'airline', 'AF', 'AFR', 'AIR FRANCE'), ('3', 'PT6H35M', 1, 'AF', '7551', 'PT2H', 0, 0, 'LHR', '4', '2023-09-10T08:55:00', 'NCE', '2', '2023-09-10T11:55:00', None, '179.05', 'EUR', 2, 'airline', 'AF', 'AFR', 'AIR FRANCE'), ('3', 'PT6H35M', 2, 'AF', '7307', 'PT1H40M', 0, 0, 'NCE', '2', '2023-09-10T14:50:00', 'CDG', '2F', '2023-09-10T16:30:00', None, '179.05', 'EUR', 2, 'airline', 'AF', 'AFR', 'AIR FRANCE'), ('4', 'PT7H30M', 1, 'AF', '7551', 'PT2H', 0, 0, 'LHR', '4', '2023-09-10T08:55:00', 'NCE', '2', '2023-09-10T11:55:00', None, '179.05', 'EUR', 2, 'airline', 'AF', 'AFR', 'AIR FRANCE'), ('4', 'PT7H30M', 2, 'AF', '7309', 'PT1H35M', 0, 0, 'NCE', '2', '2023-09-10T15:50:00', 'CDG', '2F', '2023-09-10T17:25:00', None, '179.05', 'EUR', 2, 'airline', 'AF', 'AFR', 'AIR FRANCE'), ('5', 'PT4H', 1, 'KL', '1002', 'PT1H20M', 0, 0, 'LHR', '3', '2023-09-10T08:40:00', 'AMS', None, '2023-09-10T11:00:00', None, '190.40', 'EUR', 2, 'airline', 'KL', 'KLM', 'KLM')  ... displaying 10 of 185 total bound parameter sets ...  ('100', 'PT22H30M', 1, 'A3', '603', 'PT3H35M', 0, 0, 'LHR', '2', '2023-09-10T16:35:00', 'ATH', None, '2023-09-10T22:10:00', None, '724.98', 'EUR', 2, 'airline', 'A3', 'AEE', 'AEGEAN AIR'), ('100', 'PT22H30M', 2, 'A3', '612', 'PT3H30M', 0, 0, 'ATH', None, '2023-09-11T13:35:00', 'CDG', '1', '2023-09-11T16:05:00', None, '724.98', 'EUR', 2, 'airline', 'A3', 'AEE', 'AEGEAN AIR')]]
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [ ]:
# # Assuming you've defined api_key and api_secret somewhere else
# amadeus = Client(client_id=api_key, client_secret=api_secret)

# # Defining the parameters for the flight
# params = {
#     'originLocationCode': 'LHR',
#     'destinationLocationCode': 'CDG',
#     'departureDate': '2023-09-10',  # API might require specific date format
#     'returnDate': '2023-12-10',
#     'adults': 1,
#     'children': 1,
#     'infants': 1    
#     # add or modify other parameters according to your needs
# }

# try:
#     response_flights = amadeus.shopping.flight_offers_search.get(**params)
    
# except ResponseError as error:
#     print(f"ResponseError occurred flights: {error}")
#     print(f"Error code flights: {error.code}")
#     print(f"Error message flights: {error.description}")
#     # return []  # return an empty list in case of an error

# try:
#     response_airline_lookup = amadeus.reference_data.airlines.get()

# except ResponseError as error:
#     print(f"ResponseError occurred airline lookup: {error}")
#     print(f"Error code airline lookup: {error.code}")
#     print(f"Error message airline lookup: {error.description}")

# df_flights = journey_data(response_flights.data, response_airline_lookup.data)
# df_flights
# # db = load_data(df_flights)

In [ ]:
# df_flights.to_csv("../src/flights.csv")

In [ ]:
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
from langchain.agents import AgentExecutor
from langchain.agents.agent_types import AgentType
from langchain.chat_models import ChatOpenAI


toolkit = SQLDatabaseToolkit(db=db, llm=ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613", openai_api_key=openai_key))

agent_executor = create_sql_agent(
    llm=ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613", openai_api_key=openai_key),
    toolkit=toolkit,
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
)

agent_executor.run(query)